### ISSUE TITLE
error: Terminal: environment can only contain strings

### ISSUE THREAD

**Issue by kenberkeley** [wbond/sublime_terminal#154]
`Terminal.sublime-settings`:
```
{
	// The command to execute for the terminal, leave blank for the OS default
	// See https://github.com/wbond/sublime_terminal#examples for examples
	"terminal": "D:\\Git\\git-bash.exe",

	// A list of default parameters to pass to the terminal, this can be
	// overridden by passing the "parameters" key with a list value to the args
	// dict when calling the "open_terminal" or "open_terminal_project_folder"
	// commands
	"parameters": [],

	// An environment variables changeset. Default environment variables used for the
	// terminal are inherited from sublime. Use this mapping to overwrite/unset. Use
	// null value to indicate that the environment variable should be unset.
	"env": {}
}
```

Sublime Console:
```
error: Terminal: environment can only contain strings
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 205, in on_activated
    callback.__module__, "on_activated", EVENT_TIMEOUT)
  File ".\sublime_plugin.py", line 154, in run_timed_function
    ret = f()
  File ".\sublime_plugin.py", line 204, in <lambda>
    run_timed_function(lambda: callback.on_activated(v),
  File ".\git_gutter_events.py", line 58, in on_activated
  File ".\git_gutter_events.py", line 89, in debounce
Boost.Python.ArgumentError: Python argument types in
    sublime.set_timeout(function, NoneType)
did not match C++ signature:
    set_timeout(class boost::python::api::object, int)
```

Commented the `env`, another error occurred: `error: Terminal: 'NoneType' object is not iterable`  
```
error: Terminal: 'NoneType' object is not iterable
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 205, in on_activated
    callback.__module__, "on_activated", EVENT_TIMEOUT)
  File ".\sublime_plugin.py", line 154, in run_timed_function
    ret = f()
  File ".\sublime_plugin.py", line 204, in <lambda>
    run_timed_function(lambda: callback.on_activated(v),
  File ".\git_gutter_events.py", line 58, in on_activated
  File ".\git_gutter_events.py", line 89, in debounce
Boost.Python.ArgumentError: Python argument types in
    sublime.set_timeout(function, NoneType)
did not match C++ signature:
    set_timeout(class boost::python::api::object, int)
```

**Comment by twolfson** [comment]
I'm unable to reproduce the issue but I see a code flaw we overlooked in a recent PR (#152). We don't have any fallback for `get_setting('env')` which is likely causing the issue. I'll submit/land a patch for that promptly. Sorry for the inconvenience x_x

**Comment by twolfson** [comment]
Alright, we landed a patch in #155 that should resolve the issue. When the change propagates to Package Control and it's downloaded locally, you should be back to normal. Thanks for the bug report =)

**Comment by twolfson** [comment]
Ah, damn. @kenberkeley reported in #155 the error was still persisting on ST2 (which is prob why I couldn't reproduce the error):

https://github.com/wbond/sublime_terminal/pull/155#issuecomment-270594032

**Comment by kenberkeley** [comment]
Well, maybe I am an old-fashioned man...

**Comment by twolfson** [comment]
Heh, alright. No need to close the issue -- going to still patch it. The second half was mostly my curiousity

**Comment by twolfson** [comment]
Alright, #156 is landed and released in `1.16.3`. Thanks for being so diligent to eagerly test and report back to us =)

**Comment by csxphil** [comment]
The current package control version is still at 1.16.2, is there a way for this to be installed manually, or update the package control version?

**Comment by twolfson** [comment]
Ugh, sorry. I completed the patch on my `twolfson` repo but must have forgotten to push to `wbond`/`upstream`:

https://github.com/twolfson/sublime_terminal/commit/481fef2acb4fe1e5c15211136548198a06fff2e9

I'll clone the repo and repush its commits/tags in a second. Thanks for the bump :+1:
