### ISSUE TITLE
Windows Terminal Example on readme is nowadays incorrect

### ISSUE THREAD

**Issue by EncryptEx** [wbond/sublime_terminal#218]
I've tried to use the example [here](https://github.com/wbond/sublime_terminal#windows-terminal), but in my case, the `C:/Users/yourusername/AppData/Local/Microsoft/WindowsApps/wt.exe` doesn't exist since they moved to `C:\Windows\system32\cmd.exe`.
And obvously I check it with my real Windows username.
I don't know if this change will help for everyone, but at least twice of my computers have this change.

**Comment by LuciFR1809** [comment]
Hi are you using Command Prompt or [Windows Terminal](https://github.com/microsoft/terminal) which is a different application all together

**Comment by michapixel** [comment]
MS didn't replace CMD.exe.

I myself had "C:/Users/$USER/AppData/Local/Microsoft/WindowsApps/wt.exe" as path that results in an error (file not found) now since yesterday:
```
Traceback (most recent call last):
  File "C:\Users\$USER\AppData\Roaming\Sublime Text 3\Packages\Terminal\Terminal.py", line 172, in run_terminal
    subprocess.Popen(args, cwd=cwd, env=env)
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```
I moved from Sublime 3 to 4 some days ago (but it worked at first, that's sure) ... just in case

**Comment by michapixel** [comment]
Ah, i found it:
the wt.exe in "C:/Users/$USER/AppData/Local/Microsoft/WindowsApps/" is just a symlink or something like it, which points to a folder - in my case: "Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe" inside "C:/Users/$USER/AppData/Local/Microsoft/WindowsApps/". So just append it to yout path.

I guess this is a Windows-Store special since it's the same with skype e.g.
